version: '3.8'

services:
  frontend:
    image: ${DOCKERHUB_USERNAME:-shikharprod}/run-ai:latest
    container_name: run_ai_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend

  backend:
    image: ${DOCKERHUB_USERNAME:-shikharprod}/run-ai-backend:latest
    container_name: run_ai_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql_db
      - DB_USER=root
      - DB_PASSWORD=supersecretpassword
      - DB_NAME=run_ai_db
    volumes:
      - ./main_server/credentials:/app/credentials
    depends_on:
      mysql_db:
        condition: service_healthy

  mysql_db:
    image: mysql:8.0
    container_name: run_ai_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
      MYSQL_DATABASE: run_ai_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: run_ai_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data: {} 